### ISSUE TITLE
Preprocessing of the scATAC-seq data

### ISSUE THREAD

**Issue by xwanaf** [jhu99/vipcca#1]
Hi,

I'm repeating the third data application in the paper: align scATAC-seq with scRNA-seq data. But I can not find the preprocessing codes for the scATAC-seq data in this repository. Then I go to the tutorial website which is given in "README". It seems that the preprocessing of scATAC-seq data is done in R. Follow the tutorial and the description of data processing in the paper, I still cannot repeat the results in the paper.

Did I miss something or I misunderstood the description in the paper? If the complete codes are indeed not yet public, would you mind unloading the complete codes for the preprocessing of scATAC-seq data?

**Comment by jhu99** [comment]
Thanks for your comments. @xwanaf 
The preprocessing of scATAC-seq data is exactly the same as the workflow provided by Seurat vignette at https://satijalab.org/seurat/archive/v3.0/atacseq_integration_vignette.html.
The code for reproducing the results are also provided in our github repository jhu99/vipcca_paper. 
Hopefully, these information would fix your problem.
