### ISSUE TITLE
Issues with tensorflow and keras versions with running vipcca tutorial

### ISSUE THREAD

**Issue by anashank** [jhu99/vipcca#2]
Hi, I keep running into errors while running the fit_integrate step of the code, and I realize this is occurring due to some dependency issues pertainining to the tensorflow and keras versions, even after the conda/pip installations. I tried changing the versions, but I still encounter errors. Could you please help with this? Thank you!

**Comment by jhu99** [comment]
Sorry for the late reply.  The VIPCCA has been included in our python package scbean. Please see detailed information at https://scbean.readthedocs.io/en/latest/installation.html. Please install it in a new Conda enviroment. We can offer more help if you still has problem for running it.
