### ISSUE TITLE
Conversion of signac data to h5ad

### ISSUE THREAD

**Issue by emanuelavilla** [jhu99/vipcca#3]
Hello dr. Hu,

Thanks for your tool! It will be very useful for my research. 

I have a very quick question. When you convert the scATAC object into h5ad, which data do I have to take? The peak data or the RNA data (the gene activity matrix)? 

I am asking this because when I tried to convert my scATAC data, using first peak assay and then RNA assay, R returned the same error:

_SaveH5Seurat(scATACobj, filename = "scATACobj.h5Seurat")
Creating h5Seurat file for version 3.1.5.9900
Adding counts for peaks
Adding data for peaks
Adding variable features for peaks
Adding feature-level metadata for peaks
Writing out ranges for peaks
Writing out motifs for peaks
Error in attr$write(robj) : HDF5-API Errors:
    error #000: ../../../src/H5A.c in H5Awrite(): line 619: null attribute buffer
        class: HDF5
        major: Invalid arguments to routine
        minor: Bad value_

 Any suggestions as to what I am doing wrong?
Thanks a lot

**Comment by jhu99** [comment]
Hello @emanuelavilla ，
We used the gene acitivity matrix. We first write the RNA count matrix into 10X_mtx, and read the 10X_mtx data in python using scanpy. After that, it can be easily written into h5ad. Hope it can help you!
